"""ADD PARKINGS

Revision ID: 4b947e0dbba7
Revises: 2c321f39b311
Create Date: 2025-09-27 21:45:50.164569

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4b947e0dbba7"
down_revision: Union[str, Sequence[str], None] = "2c321f39b311"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("parking", sa.Column("name", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("parking", "name")
    # ### end Alembic commands ###
