"""CHANGED BOOKING

Revision ID: 96903d4c5a37
Revises: 6192aa4ad14e
Create Date: 2025-09-28 01:01:38.838504

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "96903d4c5a37"
down_revision: Union[str, Sequence[str], None] = "6192aa4ad14e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("booking", sa.Column("start", sa.DateTime(), nullable=False))
    op.add_column("booking", sa.Column("end", sa.DateTime(), nullable=False))
    op.create_foreign_key(None, "booking", "parking", ["parking_id"], ["id"])
    op.create_foreign_key(None, "booking", "car", ["car_id"], ["id"])
    op.drop_column("booking", "date")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("booking", sa.Column("date", sa.DATETIME(), nullable=False))
    op.drop_constraint(None, "booking", type_="foreignkey")
    op.drop_constraint(None, "booking", type_="foreignkey")
    op.alter_column(
        "booking",
        "parking_id",
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.drop_column("booking", "end")
    op.drop_column("booking", "start")
    # ### end Alembic commands ###
