"""ADD BOOKINGS

Revision ID: 6bc13e437b31
Revises: 4b947e0dbba7
Create Date: 2025-09-27 23:52:29.794923

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6bc13e437b31"
down_revision: Union[str, Sequence[str], None] = "4b947e0dbba7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "parking", sa.Column("available_spots", sa.Integer(), nullable=False, default=0)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("parking", "available_spots")
    # ### end Alembic commands ###
