name: Deploy Flask App with Rollback

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            set -e

            APP_DIR=~/virodip-v2.0
            SERVICE=virodip_api.service

            echo "=== Starting deployment ==="
            cd $APP_DIR

            # Save current commit for rollback
            CURRENT_COMMIT=$(git rev-parse HEAD)
            echo "Current deployed commit: $CURRENT_COMMIT"

            # Pull latest code
            git fetch origin main
            git reset --hard origin/main

            # Update dependencies
            if [ -f "server/requirements.txt" ]; then
              source server/.venv/bin/activate
              pip install -r server/requirements.txt
              deactivate
            fi

            # Restart systemd service
            echo "Restarting service..."
            sudo systemctl restart $SERVICE
            sleep 3

            # Check if running
            if systemctl is-active --quiet $SERVICE; then
              echo "✅ Deployment successful: service is active"
              exit 0
            else
              echo "❌ Deployment failed, rolling back..."
              git reset --hard $CURRENT_COMMIT
              sudo systemctl restart $SERVICE
              sleep 3

              if systemctl is-active --quiet $SERVICE; then
                echo "⚠️ Rollback succeeded: restored previous commit $CURRENT_COMMIT"
                exit 0
              else
                echo "🚨 Rollback failed: service still inactive!"
                systemctl status $SERVICE --no-pager
                exit 1
              fi
            fi
